  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ReservaDB;encrypt=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 432367225275-qgfb3ko5sp10efnodhbsucgmdivtrim3.apps.googleusercontent.com
            client-secret: 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

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

logging:
  level:
    org:
      springframework:
        security: TRACE


# JWT Secret Key
jwt:
  secret: your-256-bit-secret
