spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=hola;encrypt=false
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 432367225275-qgfb3ko5sp10efnodhbsucgmdivtrim3.apps.googleusercontent.com
            client-secret: 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

logging:
  level:
    org:
      springframework:
        security: TRACE

# JWT Secret Key
jwt:
  secret: your-256-bit-secret
